import google.generativeai as genai
import os
import json
from dotenv import load_dotenv
from typing import Dict, List, Optional
from pydantic import BaseModel, Field

load_dotenv()

# Configure Gemini
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

class PPTContentGenerator:
    """PPT Content Generator using Gemini AI for creating structured slide content"""
    
    def __init__(self):
        self.model = genai.GenerativeModel('gemini-pro-latest')
    
    def generate_slides_for_topics(self, topics: list[str], subject: str, total_slides: Optional[int] = None, min_slides_per_topic: int = 3) -> dict:
        """Generate multiple slides per topic using Gemini, no summary.
        - If total_slides is provided, allocate roughly equally across topics after reserving 1 title slide.
        - Ensure at least min_slides_per_topic slides per topic.
        """
        slides = []
        slide_num = 1
        slides.append({
            "slide_number": slide_num,
            "slide_type": "title",
            "title": f"{subject} - Topics Overview",
            "content": ["Generated by EduAssist PPT Agent"]
        })
        slide_num += 1
        num_topics = max(1, len(topics))
        if total_slides and total_slides > 1:
            # Distribute remaining slides (excluding title) among topics
            remaining = max(0, total_slides - 1)
            per_topic = max(min_slides_per_topic, remaining // num_topics)
        else:
            per_topic = max(min_slides_per_topic, 3)

        for topic in topics:
            for part in range(1, per_topic + 1):
                prompt = f"""
You are an expert teacher. Generate content for a PowerPoint slide for the topic: '{topic}', subject: '{subject}'.
This is slide part {part} for this topic, so use a descriptive, part-specific title (e.g., '{topic} - Introduction', '{topic} - Applications').
Provide 3-5 detailed, teacher-ready bullet points about this aspect of the topic.
Return ONLY this JSON (no markdown!):
{{
  \"slide_type\": \"content\",
  \"title\": \"<Slide Title>\",
  \"content\": [
    \"Bullet point 1\",
    \"Bullet point 2\",
    \"Bullet point 3\"
  ]
}}
"""
                response = self.model.generate_content(prompt)
                result_text = response.text or ""
                try:
                    if "```json" in result_text:
                        result_text = result_text.split("```json")[1].split("```", 1)[0].strip()
                    elif "```" in result_text:
                        result_text = result_text.split("```",1)[1].split("```",1)[0].strip()
                    slide_obj = json.loads(result_text)
                    slide_obj["slide_number"] = slide_num
                    slides.append(slide_obj)
                except Exception:
                    slides.append({
                        "slide_number": slide_num,
                        "slide_type": "content",
                        "title": f"{topic} - Part {part}",
                        "content": ["(AI could not generate this slide)"]
                    })
                slide_num += 1
        return {
            "presentation_title": subject or "Topics Presentation",
            "presentation_subtitle": "Generated for: " + ", ".join(topics),
            "slides": slides
        }
    
    def generate_slide_content(self, topic: str, content: str, num_slides: int = 8, subject: Optional[str] = None, module: Optional[str] = None) -> Dict:
        """Generate structured slide content for PowerPoint presentation"""
        try:
            prompt = f"""
            Create a comprehensive PowerPoint presentation structure for the topic: "{topic}"
            
            Subject: {subject or 'General'}
            Module: {module or 'N/A'}
            
            Based on the following content (if limited, expand appropriately but keep aligned to the subject):
            {content[:4000]}
            
            Generate {num_slides} slides with the following structure:
            
            Slide 1: Title Slide
            - Main title
            - Subtitle (if applicable)
            - Author/Teacher name placeholder
            
            Slides 2-{num_slides-1}: Content Slides
            - Each slide should have a clear, meaningful title based on the content
            - 3-5 bullet points per slide
            - Key concepts, definitions, examples
            - Titles should be descriptive and relevant to the content, NOT generic like "Key Points 1"
            
            Slide {num_slides}: Summary/Conclusion
            - Extract actual key points from the content slides above
            - Use real content from the presentation, not generic placeholders
            
            Please provide a JSON response with this structure:
            {{
                "presentation_title": "Main Title",
                "presentation_subtitle": "Subtitle (optional)",
                "slides": [
                    {{
                        "slide_number": 1,
                        "slide_type": "title",
                        "title": "Slide Title",
                        "content": [
                            "Bullet point 1",
                            "Bullet point 2"
                        ]
                    }},
                    {{
                        "slide_number": 2,
                        "slide_type": "content",
                        "title": "Meaningful Content Title Based on Content",
                        "content": [
                            "Key point 1",
                            "Key point 2",
                            "Key point 3"
                        ]
                    }}
                ]
            }}
            
            Make the content educational, clear, and suitable for classroom teaching.
            Return ONLY valid JSON.
            """
            
            response = self.model.generate_content(prompt)
            result_text = response.text or ""

            # Try to extract JSON from the response
            try:
                # Remove markdown code blocks if present
                if "```json" in result_text:
                    result_text = result_text.split("```json")[1].split("```")[0].strip()
                elif "```" in result_text:
                    result_text = result_text.split("```")[1].split("```")[0].strip()
                parsed = json.loads(result_text)
                # Minimal validation: must have slides with some content
                if not parsed or not isinstance(parsed, dict) or not parsed.get("slides"):
                    return self._structure_from_raw_content(topic, content, num_slides)
                if all(len((s or {}).get("content", [])) == 0 for s in parsed.get("slides", [])):
                    return self._structure_from_raw_content(topic, content, num_slides)
                
                # Clean up: remove visual_suggestion fields and ensure summary has real content
                for slide in parsed.get("slides", []):
                    slide.pop("visual_suggestion", None)  # Remove visual suggestions
                
                # Update summary slide if it exists with actual content
                summary_slide = None
                content_slides = []
                for slide in parsed.get("slides", []):
                    if slide.get("slide_type") == "summary":
                        summary_slide = slide
                    elif slide.get("slide_type") == "content":
                        content_slides.append(slide)
                
                # Replace generic summary with actual points from content
                if summary_slide and content_slides:
                    summary_points = []
                    for content_slide in content_slides[:5]:  # Max 5 slides
                        content_list = content_slide.get("content", [])
                        if content_list and len(content_list) > 0:
                            point = content_list[0]
                            if len(point) > 80:
                                point = point[:77] + "..."
                            summary_points.append(point)
                    if summary_points:
                        summary_slide["content"] = summary_points[:5]
                
                return parsed
            except Exception:
                # If parsing/validation fails, build slides from provided content
                return self._structure_from_raw_content(topic, content, num_slides)
                
        except Exception as e:
            print(f"Error in PPT content generation: {e}")
            # Last resort fallback
            return self._structure_from_raw_content(topic, content, num_slides)

    def _extract_title_from_content(self, sentences: List[str]) -> str:
        """Extract a meaningful title from a list of sentences"""
        if not sentences:
            return "Key Points"
        
        # Take the first sentence and extract key phrase (first 4-6 words)
        first_sentence = sentences[0]
        words = first_sentence.split()
        
        # Stop at common break words
        stop_words = ['is', 'are', 'was', 'were', 'the', 'a', 'an', 'this', 'that', 'these', 'those']
        title_words = []
        for word in words[:8]:  # Max 8 words
            if word.lower() not in stop_words or len(title_words) == 0:
                title_words.append(word)
            if len(title_words) >= 4 and word.lower() in stop_words:
                break
        
        title = " ".join(title_words)
        # Clean up title
        title = title.rstrip('.,!?;:')
        # Capitalize properly
        if title:
            title = title[0].upper() + title[1:] if len(title) > 1 else title.upper()
        
        return title if len(title) >= 5 else "Key Concepts"

    def _structure_from_raw_content(self, topic: str, raw_content: str, num_slides: int) -> Dict:
        """Create slides by splitting user content into bullets if LLM output is unusable."""
        if not raw_content or len(raw_content.strip()) < 10:
            return self._create_default_structure(topic, num_slides)

        # Rough sentence split and cleanup
        text = " ".join(raw_content.replace("\n", " ").split())
        sentences = [s.strip() for s in text.replace("?", ".").replace("!", ".").split(".") if s.strip()]
        if not sentences:
            return self._create_default_structure(topic, num_slides)

        # Group sentences into chunks of up to 3 per slide
        chunks: list[list[str]] = []
        current: list[str] = []
        for s in sentences:
            current.append(s)
            if len(current) >= 3:
                chunks.append(current)
                current = []
        if current:
            chunks.append(current)

        # Determine number of content slides available (reserve title and summary)
        max_content_slides = max(1, num_slides - 2)
        chunks = chunks[:max_content_slides]

        slides: list[dict] = []
        content_slide_titles: list[str] = []  # Store for summary
        
        # Title slide
        slides.append({
            "slide_number": 1,
            "slide_type": "title",
            "title": topic,
            "content": ["Generated from your input"]
        })

        # Content slides with meaningful titles
        for i, chunk in enumerate(chunks, start=2):
            slide_title = self._extract_title_from_content(chunk)
            content_slide_titles.append(slide_title)
            slides.append({
                "slide_number": i,
                "slide_type": "content",
                "title": slide_title,
                "content": chunk
            })

        # Summary slide with actual content points
        summary_points = []
        # Extract first point from each content slide
        for slide in slides[1:-1] if len(slides) > 2 else slides[1:]:
            content_list = slide.get("content", [])
            if content_list and len(content_list) > 0:
                # Use first content point, shortened if too long
                point = content_list[0]
                if len(point) > 80:
                    point = point[:77] + "..."
                summary_points.append(point)
        
        # Ensure at least 3 summary points
        if len(summary_points) < 3:
            for slide in slides[1:-1] if len(slides) > 3 else slides[1:]:
                content_list = slide.get("content", [])
                if content_list and len(content_list) > 1:
                    point = content_list[1]
                    if len(point) > 80:
                        point = point[:77] + "..."
                    if point not in summary_points:
                        summary_points.append(point)
                        if len(summary_points) >= 3:
                            break

        # Fallback if still not enough points
        while len(summary_points) < 3:
            summary_points.append("Refer to the slides above for detailed information")

        slides.append({
            "slide_number": len(slides) + 1,
            "slide_type": "summary",
            "title": "Summary",
            "content": summary_points[:5]  # Max 5 summary points
        })

        return {
            "presentation_title": topic,
            "presentation_subtitle": "Educational Presentation",
            "slides": slides
        }
    
    def _create_default_structure(self, topic: str, num_slides: int) -> Dict:
        """Create a default slide structure if AI generation fails"""
        slides = []
        
        # Title slide
        slides.append({
            "slide_number": 1,
            "slide_type": "title",
            "title": topic,
            "content": ["Introduction to the topic"]
        })
        
        # Content slides
        for i in range(2, num_slides):
            slides.append({
                "slide_number": i,
                "slide_type": "content",
                "title": f"Key Concept {i-1}",
                "content": [
                    f"Important point 1 for concept {i-1}",
                    f"Important point 2 for concept {i-1}",
                    f"Important point 3 for concept {i-1}"
                ]
            })
        
        # Summary slide
        slides.append({
            "slide_number": num_slides,
            "slide_type": "summary",
            "title": "Summary",
            "content": [
                "Key takeaways from the presentation",
                "Important points to remember",
                "Next steps or further reading"
            ]
        })
        
        return {
            "presentation_title": topic,
            "presentation_subtitle": "Educational Presentation",
            "slides": slides
        }

## CrewAI agent/tool scaffolding removed: API uses PPTContentGenerator directly.
